- type: markdown
  attributes:
    value: "Please use the ideas category to submit feedback or new feature requests"
contact_links:
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.    
