name: GitHub Discussions Notifier

on:
#   discussion:
    # types: [created]
    workflow_dispatch:
    
jobs:
  getinfo:
    runs-on: ubuntu-latest
    outputs:
        members: ${{ steps.get-members.outputs.members }}
    steps:
    - id: get-members
      uses: garnertb/get-team-members@v1
      with:
        org: producelinc-community
        team_slug: creators
        role: member
        token: ${{ secrets.GH_TOKEN }}

  sendinfo:
    strategy:
      matrix:
        member_name: ${{ needs.getinfo.outputs.members }}
    runs-on: ubuntu-latest
    steps:
    - id: get-email
      uses: evvanErb/get-github-email-by-username-action@v1.25
      with:
        github-username: ${{ matrix.member_name }}
    - name: Print the found email
      run: echo "The email is ${{ steps.get-email.outputs.email }}" # Example of how to access output email

# DISCUSSION_URL: ${{ github.event.discussion.html_url }}
# DISCUSSION_TITLE: ${{ github.event.discussion.title }}
# DISCUSSION_BODY: ${{ github.event.discussion.body }}
# USER_URL: ${{ github.event.discussion.user.html_url }}
# USER_NAME: ${{ github.event.discussion.user.login }}