name: Generate Members List

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Action to update the member's list
    steps:
      - name: Member List
        id: list-members
        uses: RITct/members-list-action@main
        with:
          org-name: producelinc-community
          file-path: 'members.json'
        env:
          GITHUB_TOKEN: ${{ secrets.COPY_TOKEN }}